# Generated by Django 4.2.17 on 2024-12-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_timestamp_message_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
