# Generated by Django 5.1.4 on 2024-12-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
