# Generated by Django 4.2.17 on 2024-12-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_countproduct_order_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
