# Generated by Django 4.2.17 on 2024-12-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='prise',
        ),
    ]
