# Generated by Django 4.2.17 on 2024-12-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_adminselllist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
