# Generated by Django 5.1.4 on 2024-12-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
