# Generated by Django 5.1.4 on 2024-12-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminselllist',
            name='flyers',
            field=models.IntegerField(default=0),
        ),
    ]
