# Generated by Django 5.1.4 on 2024-12-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='time',
            field=models.DateField(),
        ),
    ]
