# Generated by Django 5.1.4 on 2024-12-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_time_sell_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
